In [9]:
%matplotlib notebook

import os
import sys
src_module_path = os.path.abspath(os.path.join('..\src'))
sys.path.append(src_module_path)

price_data_module_path = os.path.abspath(os.path.join('..\data\external'))
sys.path.append(price_data_module_path)

from matplotlib import pyplot as plt
import numpy as np

from features import _data_utils as dutils

In [10]:
dutils.PATH_TO_DATA = '../data/raw/'
house = "dataid1103.csv"
day = 1
numberOfDays = 5
x, grid, cons, prod, ids = dutils.init_data(house, numberOfDays, day)

In [14]:
for idx, (oneX, oneGrid, oneProd, oneCons) in enumerate(zip(np.split(x, 5), np.split(grid, 5), np.split(prod, 5), np.split(cons, 5))):
    print(idx)
    print(oneX)
    print(oneGrid)
    print(oneProd)
    print(oneCons)

0
[datetime.datetime(2014, 1, 1, 0, 0) datetime.datetime(2014, 1, 1, 1, 0)
 datetime.datetime(2014, 1, 1, 2, 0) datetime.datetime(2014, 1, 1, 3, 0)
 datetime.datetime(2014, 1, 1, 4, 0) datetime.datetime(2014, 1, 1, 5, 0)
 datetime.datetime(2014, 1, 1, 6, 0) datetime.datetime(2014, 1, 1, 7, 0)
 datetime.datetime(2014, 1, 1, 8, 0) datetime.datetime(2014, 1, 1, 9, 0)
 datetime.datetime(2014, 1, 1, 10, 0) datetime.datetime(2014, 1, 1, 11, 0)
 datetime.datetime(2014, 1, 1, 12, 0) datetime.datetime(2014, 1, 1, 13, 0)
 datetime.datetime(2014, 1, 1, 14, 0) datetime.datetime(2014, 1, 1, 15, 0)
 datetime.datetime(2014, 1, 1, 16, 0) datetime.datetime(2014, 1, 1, 17, 0)
 datetime.datetime(2014, 1, 1, 18, 0) datetime.datetime(2014, 1, 1, 19, 0)
 datetime.datetime(2014, 1, 1, 20, 0) datetime.datetime(2014, 1, 1, 21, 0)
 datetime.datetime(2014, 1, 1, 22, 0) datetime.datetime(2014, 1, 1, 23, 0)]
[ 0.21148333  0.27803333  0.34985     0.34851667  0.35096667  0.32765
  0.63326667  0.62026667 -0.1084     

In [17]:
int (len(x) / 24)

5

In [44]:
a = np.array([(0,0),(0,0),(0,0),(0,9)])
b = np.array([(1,1),(1,1)])
c = np.array([(0,0)])

a = np.append(c,b, axis=0)
a

array([[0, 0],
       [1, 1],
       [1, 1]])

In [45]:
a = np.array([])
b = np.array([1,2])

a = np.append(a,b)
a

array([ 1.,  2.])

In [50]:
a = np.arange(10)
a[:3]

array([0, 1, 2])

In [51]:
a = np.array([(1,0),(1,0),(1,0),(1,9)])
a

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 9]])

In [66]:
lb = a[:,0]
lb

array([1, 1, 1, 1])

In [27]:
import numpy as np

a = np.array([11, 22, 33, 44, 55, 66, 77, 88])

# np.hstack((a[1:-1],a[2:]))

# firstTwo = np.split(a[:-2], int(len(a)/2) -1)
# secondTwo = np.split(a[1:-1], int(len(a)/2) -1)

firstTwo = np.split(a[:-1], len(a)-1)
secondTwo = np.split(a[1:], len(a)-1)

print(firstTwo)
print(secondTwo)
np.hstack((firstTwo, secondTwo))



[array([11]), array([22]), array([33]), array([44]), array([55]), array([66]), array([77])]
[array([22]), array([33]), array([44]), array([55]), array([66]), array([77]), array([88])]


array([[11, 22],
       [22, 33],
       [33, 44],
       [44, 55],
       [55, 66],
       [66, 77],
       [77, 88]])